version: "2"
services:
  bombermanBackend:
    image: "node:8"
    user: "node"
    working_dir: /home/app/bomberman/
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/app/bomberman/
    expose:
      - "8081"
    command: "npm start"
